### ISSUE TITLE
Path not correct

### ISSUE THREAD

**Issue by PackLack197** [cjwatson/minecraft-convert-local-player#3]
I tried to use the compare worlds script, but there's an exception, and it shows that the path that I passed into the script has 2 slashes before db. It says that the folder does not exist.

`C:\Python>python compare-worlds.py Thisisaworld ThisisaworldSERVER
Traceback (most recent call last):
  File "C:\Python\compare-worlds.py", line 61, in <module>
    new_db = ldb.open(os.path.join(args.new_world, "db"))
  File "C:\Python\bedrock\leveldb.py", line 153, in open
    _checkError(error)
  File "C:\Python\bedrock\leveldb.py", line 135, in _checkError
    raise Exception(message)
Exception: b'Invalid argument: ThisisaworldSERVER\\db: does not exist (create_if_missing is false)'`

**Comment by PackLack197** [comment]
Nevermind, figured it out
